using System.Text;
using SurrealDb.Net.Models.Response;

namespace SurrealDb.Net.Tests;

/// <summary>
/// A record type that implements <see cref="IRecord"/> directly (as opposed to inheriting
/// <see cref="Record"/>) and does NOT redeclare the <c>[CborProperty("id")]</c> /
/// <c>[CborIgnoreIfDefault]</c> attributes carried by <see cref="IRecord.Id"/>. This mirrors the
/// scenario reported in https://github.com/surrealdb/surrealdb.net/issues/212, where such a class
/// ends up with its <c>Id</c> serialized twice: once as the literal member name "Id" (riding
/// along in the CBOR payload) and once as the RPC's own "id" positional argument.
/// </summary>
public class RawIdRecord : IRecord
{
    public RecordId? Id { get; set; }

    public string Name { get; set; } = string.Empty;
}

public class CreateTests
{
    [Test]
    [ConnectionStringFixtureGenerator]
    public async Task ShouldCreateEmptyWithoutData(string connectionString)
    {
        IEnumerable<Empty>? list = null;
        Empty? result = null;

        Func<Task> func = async () =>
        {
            await using var surrealDbClientGenerator = new SurrealDbClientGenerator();
            var dbInfo = surrealDbClientGenerator.GenerateDatabaseInfo();

            await using var client = surrealDbClientGenerator.Create(connectionString);
            await client.Use(dbInfo.Namespace, dbInfo.Database);

            await client.ApplySchemaAsync(SurrealSchemaFile.Post);

            result = await client.Create<Empty>("empty");

            list = await client.Select<Empty>("empty");
        };

        await func.Should().NotThrowAsync();

        list.Should().NotBeNull().And.HaveCount(1);

        result.Should().NotBeNull();
    }

    [Test]
    [ConnectionStringFixtureGenerator]
    public async Task ShouldCreatePostWithAutogeneratedId(string connectionString)
    {
        IEnumerable<Post>? list = null;
        Post? result = null;

        Func<Task> func = async () =>
        {
            await using var surrealDbClientGenerator = new SurrealDbClientGenerator();
            var dbInfo = surrealDbClientGenerator.GenerateDatabaseInfo();

            await using var client = surrealDbClientGenerator.Create(connectionString);
            await client.Use(dbInfo.Namespace, dbInfo.Database);

            await client.ApplySchemaAsync(SurrealSchemaFile.Post);

            var post = new Post
            {
                Title = "A new article",
                Content = "This is a new article created using the .NET SDK",
            };

            result = await client.Create("post", post);

            list = await client.Select<Post>("post");
        };

        await func.Should().NotThrowAsync();

        list.Should().NotBeNull().And.HaveCount(3);

        result.Should().NotBeNull();
        result!.Title.Should().Be("A new article");
        result!.Content.Should().Be("This is a new article created using the .NET SDK");
        result!.CreatedAt.Should().NotBeNull();
        result!.Status.Should().Be("DRAFT");
    }

    [Test]
    [ConnectionStringFixtureGenerator]
    public async Task ShouldCreatePostWithPredefinedId(string connectionString)
    {
        IEnumerable<Post>? list = null;
        Post? result = null;

        Func<Task> func = async () =>
        {
            await using var surrealDbClientGenerator = new SurrealDbClientGenerator();
            var dbInfo = surrealDbClientGenerator.GenerateDatabaseInfo();

            await using var client = surrealDbClientGenerator.Create(connectionString);
            await client.Use(dbInfo.Namespace, dbInfo.Database);

            await client.ApplySchemaAsync(SurrealSchemaFile.Post);

            var post = new Post
            {
                Id = new RecordIdOfString("post", "another"),
                Title = "A new article",
                Content = "This is a new article created using the .NET SDK",
            };

            result = await client.Create(post);

            list = await client.Select<Post>("post");
        };

        await func.Should().NotThrowAsync();

        list.Should().NotBeNull().And.HaveCount(3);

        result.Should().NotBeNull();
        result!.Title.Should().Be("A new article");
        result!.Content.Should().Be("This is a new article created using the .NET SDK");
        result!.CreatedAt.Should().NotBeNull();
        result!.Status.Should().Be("DRAFT");

        var anotherPost = list!.First(p => p.Id! == ("post", "another"));

        anotherPost.Should().NotBeNull();
        anotherPost!.Title.Should().Be("A new article");
        anotherPost!.Content.Should().Be("This is a new article created using the .NET SDK");
        anotherPost!.CreatedAt.Should().NotBeNull();
        anotherPost!.Status.Should().Be("DRAFT");
    }

    [Test]
    [ConnectionStringFixtureGenerator]
    public async Task ShouldCreateMultiplePosts(string connectionString)
    {
        IEnumerable<Post>? list = null;

        Func<Task> func = async () =>
        {
            await using var surrealDbClientGenerator = new SurrealDbClientGenerator();
            var dbInfo = surrealDbClientGenerator.GenerateDatabaseInfo();

            await using var client = surrealDbClientGenerator.Create(connectionString);
            await client.Use(dbInfo.Namespace, dbInfo.Database);

            await client.ApplySchemaAsync(SurrealSchemaFile.Post);

            var posts = new List<Post>
            {
                new Post
                {
                    Id = new RecordIdOfString("post", "A"),
                    Title = "An article",
                    Content = "This is a new article",
                },
                new Post
                {
                    Id = new RecordIdOfString("post", "B"),
                    Title = "An article",
                    Content = "This is a new article",
                },
                new Post
                {
                    Id = new RecordIdOfString("post", "C"),
                    Title = "An article",
                    Content = "This is a new article",
                },
            };

            var tasks = posts.Select(p => client.Create(p));
            await Task.WhenAll(tasks.ToArray());

            list = await client.Select<Post>("post");
        };

        await func.Should().NotThrowAsync();

        list.Should().NotBeNull().And.HaveCount(5);
    }

    [Test]
    [ConnectionStringFixtureGenerator]
    public async Task ShouldCreatePostUsingStringRecordId(string connectionString)
    {
        IEnumerable<Post>? list = null;
        Post? result = null;

        Func<Task> func = async () =>
        {
            await using var surrealDbClientGenerator = new SurrealDbClientGenerator();
            var dbInfo = surrealDbClientGenerator.GenerateDatabaseInfo();

            await using var client = surrealDbClientGenerator.Create(connectionString);
            await client.Use(dbInfo.Namespace, dbInfo.Database);

            await client.ApplySchemaAsync(SurrealSchemaFile.Post);

            var post = new Post
            {
                Title = "A new article",
                Content = "This is a new article created using the .NET SDK",
            };

            result = await client.Create<Post, Post>(new StringRecordId("post:new"), post, default);

            list = await client.Select<Post>("post");
        };

        await func.Should().NotThrowAsync();

        list.Should().NotBeNull().And.HaveCount(3);

        result.Should().NotBeNull();
        result!.Title.Should().Be("A new article");
        result!.Content.Should().Be("This is a new article created using the .NET SDK");
        result!.CreatedAt.Should().NotBeNull();
        result!.Status.Should().Be("DRAFT");
    }

    [Test]
    [ConnectionStringFixtureGenerator]
    public async Task ShouldCreateRecordImplementingIRecordDirectlyWithoutDuplicateIdField(
        string connectionString
    )
    {
        List<string>? fieldNames = null;

        Func<Task> func = async () =>
        {
            await using var surrealDbClientGenerator = new SurrealDbClientGenerator();
            var dbInfo = surrealDbClientGenerator.GenerateDatabaseInfo();

            await using var client = surrealDbClientGenerator.Create(connectionString);
            await client.Use(dbInfo.Namespace, dbInfo.Database);

            var record = new RawIdRecord
            {
                Id = new RecordIdOfString("raw_id_record", "one"),
                Name = "Alice",
            };

            await client.Create(record);

            var response = await client.RawQuery(
                "SELECT VALUE object::keys($this) FROM raw_id_record;"
            );

            var okResult = (SurrealDbOkResult)response[0];
            fieldNames = okResult.GetValue<List<List<string>>>()!.Single();
        };

        await func.Should().NotThrowAsync();

        fieldNames.Should().NotBeNull();
        fieldNames!
            .Count(fieldName => string.Equals(fieldName, "id", StringComparison.OrdinalIgnoreCase))
            .Should()
            .Be(1);
        fieldNames.Should().NotContain("Id");
    }
}
