[package]
name = "surreal_rocksdb"
publish = false
edition = "2024"
rust-version = "1.85.0"
license-file = "../../LICENSE"
resolver = "2"

[dependencies]
shared = { path = "../shared", features = ["rocksdb"] }

[lib]
crate-type = ["cdylib"]
