[package]
name = "surreal_memory"
publish = false
version = "2.0.4"
edition = "2021"
rust-version = "1.80.1"
license-file = "../../LICENSE"
resolver = "2"

[dependencies]
shared = { path = "../shared", features = ["memory"] }

[lib]
crate-type = ["cdylib"]
