// <auto-generated/>

#nullable enable

namespace SurrealDb.MinimalApis.Extensions;

/// <summary>
/// A flag to select which HTTP requests are enabled on generated Minimal Api endpoints using MapSurrealEndpoints.
/// </summary>
[Flags]
public enum SurrealDbMinimalApisRequests
{
    /// <summary>
    /// No requests enabled.
    /// </summary>
    None = 0,

    /// <summary>
    /// Enable HTTP GET request to select all records from a SurrealDB table.
    /// </summary>
    GetAll = 1 << 0,

    /// <summary>
    /// Enable HTTP GET request to select a single record from a SurrealDB table.
    /// </summary>
    GetSingle = 1 << 1,

    /// <summary>
    /// Enable HTTP POST request to create a new record in a SurrealDB table.
    /// </summary>
    Post = 1 << 2,

    /// <summary>
    /// Enable HTTP PUT request to update a record in a SurrealDB table.
    /// </summary>
    Put = 1 << 3,

    /// <summary>
    /// Enable HTTP PATCH request to patch all records in a SurrealDB table.
    /// </summary>
    PatchAll = 1 << 4,

    /// <summary>
    /// Enable HTTP PATCH request to patch a single record in a SurrealDB table.
    /// </summary>
    PatchSingle = 1 << 5,

    /// <summary>
    /// Enable HTTP DELETE request to delete all records from a SurrealDB table.
    /// </summary>
    DeleteAll = 1 << 6,

    /// <summary>
    /// Enable HTTP DELETE request to delete a single record from a SurrealDB table.
    /// </summary>
    DeleteSingle = 1 << 7,

    /// <summary>
    /// Enable all HTTP GET requests (select all records or a single record from a table).
    /// </summary>
    Queries = GetAll | GetSingle,

    /// <summary>
    /// Enable all HTTP requests that mutate data (POST, PUT, PATCH, DELETE).
    /// </summary>
    Mutations = Post | Put | PatchAll | PatchSingle | DeleteAll | DeleteSingle,

    /// <summary>
    /// Enable all HTTP requests.
    /// </summary>
    All = Queries | Mutations,
}
