// <auto-generated/>

#nullable enable

namespace SurrealDb.MinimalApis.Extensions;

/// <summary>
/// A set of options to customize configuration of generated Minimal Api endpoints using MapSurrealEndpoints.
/// </summary>
public sealed class SurrealDbMinimalApisOptions
{
    /// <summary>
    /// Selects which HTTP requests are enabled on the generated endpoints.
    /// Defaults to <see cref="SurrealDbMinimalApisRequests.All"/>.
    /// </summary>
    public SurrealDbMinimalApisRequests Requests { get; set; } = SurrealDbMinimalApisRequests.All;

    /// <summary>
    /// A set of tags to be used to document the generated endpoints using OpenAPI.
    /// </summary>
    public string[]? Tags { get; set; }

    /// <summary>
    /// The name of the SurrealDB table to be used in the generated endpoints.
    /// Defaults to the type name.
    /// </summary>
    public string? TableName { get; set; }
}
