name: Benchmark PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download SurrealDB
        run: curl --proto '=https' --tlsv1.2 -sSf https://install.surrealdb.com | sh

      - name: Run SurrealDB root
        run: surreal start --user root --pass root memory --auth --allow-guests &

      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Execute benchmarks
        run: sudo dotnet run -c Release --project SurrealDb.Net.Benchmarks --filter '*'

      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: "benchmarkdotnet"
          output-file-path: BenchmarkDotNet.Artifacts/results/Combined.Benchmarks.json
          external-data-json-path: ./cache/benchmark-data.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          summary-always: true
