name: Benchmark Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Download SurrealDB
        run: curl --proto '=https' --tlsv1.2 -sSf https://install.surrealdb.com | sh -s

      - name: Run SurrealDB root
        run: surreal start --user root --pass root memory --allow-guests &

      - name: Setup dotnet 10.0
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5
        with:
          dotnet-version: "10.0.x"

      - name: Execute Remote benchmarks
        run: sudo dotnet run -c Release --project SurrealDb.Net.Benchmarks.Remote --filter '*'

      - name: Download previous benchmark data
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@a7bc2366eda11037936ea57d811a43b3418d3073 # v1
        with:
          tool: "benchmarkdotnet"
          output-file-path: BenchmarkDotNet.Artifacts/results/Combined.Benchmarks.json
          external-data-json-path: ./cache/benchmark-data.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          summary-always: true
